-- AL HARAMAIN AMBER OUD
INSERT INTO perfumes (name, brand, description, image_url, fragrance_family, gender, top_notes, middle_notes, base_notes) VALUES
('Amber Oud', 'Al Haramain', 'Fragancia oriental amaderada unisex lanzada en 2018. La fragancia original que da nombre a la colección. Inspirada en Interlude Man de Amouage. Combina frescura aromática con especias cálidas y una base ambarada resinosa de gran profundidad.', '/images/al-haramain/amber-oud/default.avif', 'Oriental', 'Unisex', 'Romero, Cedro, Bergamota, Limón', 'Especias, Cedro, Madera de guayaco', 'Ámbar, Resinas, Almizcle'),

('Amber Oud Aqua Dubai', 'Al Haramain', 'Fragancia aromática frutal unisex lanzada en 2024. Captura la esencia del encanto costero de Dubái. Abre con bergamota, notas verdes y mandarina como la luz del sol sobre el agua.', '/images/al-haramain/amber-oud/aqua-dubai.avif', 'Aromatic Fruity', 'Unisex', 'Bergamota, Notas verdes, Mandarina', 'Melón, Ámbar, Grosella negra, Piña', 'Almizcle, Petitgrain, Gálbano, Vainilla'),

('Amber Oud Black Edition', 'Al Haramain', 'Fragancia oriental amaderada unisex lanzada en 2023. Sensual, cuero, madera y floral. Con sus profundos elementos de oud, dura y deja su marca. Proyecta poder y misterio. Rendimiento extraordinario.', '/images/al-haramain/amber-oud/black-edition.avif', 'Oriental', 'Unisex', 'Cardamomo, Lavanda, Notas amaderadas', 'Cuero, Ámbar, Haba tonka', 'Benjuí, Vetiver, Ámbar gris'),

('Amber Oud Bleu Edition', 'Al Haramain', 'Fragancia fresca especiada unisex lanzada en 2022. Inspirada en Bleu de Chanel. Abre con pomelo, limón, menta y pimienta rosa vigorizantes. El corazón de jengibre, vetiver y jazmín añade profundidad. Base amaderada rica y envolvente.', '/images/al-haramain/amber-oud/bleu-edition.avif', 'Fresh', 'Unisex', 'Pomelo, Limón, Menta, Pimienta rosa', 'Jengibre, Vetiver, Jazmín', 'Olíbano, Sándalo, Cedro, Pachulí'),

('Amber Oud Dubai Night', 'Al Haramain', 'Fragancia oriental amaderada lanzada en 2024 en concentración Extrait de Parfum. Inspirada en las noches de Dubái. La bergamota, azafrán y elemí abren con anticipación. El oud, rosa búlgara y lirio del valle evocan romance y misterio.', '/images/al-haramain/amber-oud/dubai-night.avif', 'Oriental', 'Men', 'Azafrán, Bergamota, Elemí', 'Oud, Rosa búlgara, Lirio de los valles', 'Haba tonka, Ámbar, Almizcle blanco, Musgo de roble'),

('Amber Oud Gold Edition', 'Al Haramain', 'Fragancia ámbar vainillada unisex lanzada en 2018. Inspirada en Erba Pura de Xerjoff. Abre con bergamota fresca y notas verdes. El corazón revela melón, piña, acorde gourmand y ámbar. La base de vainilla, almizcle y notas amaderadas deja una estela lujosa e inolvidable.', '/images/al-haramain/amber-oud/gold-edition.avif', 'Oriental Vanilla', 'Unisex', 'Bergamota, Notas verdes', 'Melón, Piña, Ámbar, Acorde gourmand', 'Vainilla, Almizcle, Notas amaderadas');


-- ARMAF
INSERT INTO perfumes (name, brand, description, image_url, fragrance_family, gender, top_notes, middle_notes, base_notes) VALUES

-- ODYSSEY LINE
('Odyssey Mandarin Sky Vintage', 'Armaf', 'Reinterpretación más contemplativa del Mandarin Sky original. Abre con mandarina y cítricos vibrantes, evoluciona a florales con especias cálidas y cierra con ámbar suave y maderas.', '/images/armaf/odyssey/mandarin-sky-vintage.avif', 'Oriental', 'Unisex', 'Mandarina, Notas Cítricas', 'Notas Florales, Especias Cálidas', 'Ámbar, Maderas Suaves'),
('Odyssey Mandarin Sky', 'Armaf', 'Fragancia fresca y gourmand para hombres de 2023. Abre con mandarina brillante y evoluciona a caramelo suave y haba tonka. Inspirada en el DNA de JPG Scandal.', '/images/armaf/odyssey/mandarin-sky.avif', 'Fresh', 'Men', 'Mandarina, Naranja, Azafrán, Salvia', 'Caramelo, Haba Tonka, Caléndula', 'Ambroxan, Cedro, Vetiver'),
('Odyssey Mandarin Sky Elixir', 'Armaf', 'Versión elixir del popular Mandarin Sky. Más oscura y compleja, con notas orientales amaderadas que rodean la mandarina brillante original.', '/images/armaf/odyssey/mandarin-sky-elixir.avif', 'Oriental', 'Men', 'Mandarina, Cítricos', 'Especias, Florales', 'Ámbar, Vainilla, Madera'),
('Odyssey Bahamas', 'Armaf', 'Escapada tropical acuática de 2025. Frutas jugosas, algas y notas marinas que evocan un carnaval caribeño libre y vibrante.', '/images/armaf/odyssey/bahamas.avif', 'Fresh', 'Unisex', 'Cantalupo, Melón, Algas, Sal, Manzana Granny Smith, Pera, Ciruela', 'Notas Acuáticas, Musgo de Roble, Lirio de Agua, Incienso', 'Almizcle, Ámbar, Cedro, Azúcar'),
('Odyssey Marshmallow', 'Armaf', 'Nube de dulzura gourmand de 2025. Frutal y cremoso, con malvavisco, frutos del bosque y una base de mascarpone, pralinée y vainilla irresistible.', '/images/armaf/odyssey/marshmallow.avif', 'Floral', 'Unisex', 'Coco, Manzana, Limón, Peonía, Lirio de los Valles', 'Malvavisco, Fresa, Melocotón, Albaricoque, Frambuesa, Flor de Naranja', 'Mascarpone, Praliné, Vainilla, Almizcle, Haba Tonka, Ámbar'),
('Odyssey Artisto', 'Armaf', 'Fusión artística woody-aromática de 2025. Apertura de bergamota y salvia, corazón tropical de coco y canela, base cálida de ámbar y vainilla. Muy cercano al DNA de JPG Le Beau.', '/images/armaf/odyssey/artisto.avif', 'Woody Aromatic', 'Unisex', 'Bergamota, Notas Avellanas, Salvia', 'Coco, Frutas Tropicales, Canela', 'Ámbar, Vainilla, Haba Tonka'),
('Odyssey Mega Man', 'Armaf', 'Fragancia amaderada aromática fresca de 2023. Apertura cítrica energizante con un corazón de piña y hierbas que evoluciona a una base limpia de almizcle y cedro. Inspirado en YSL Y.', '/images/armaf/odyssey/mega-man.avif', 'Woody', 'Men', 'Naranja, Bergamota, Limón, Jengibre, Menta', 'Piña, Salvia, Enebro, Geranio', 'Almizcle, Cedro, Haba Tonka, Vetiver'),
('Odyssey Limoni', 'Armaf', 'Fragancia cítrica fresca y energizante de 2024. Inspirada en el DNA de Louis Vuitton. Abre con limón brillante y cítricos y seca en un té suave y almizcle.', '/images/armaf/odyssey/limoni-fresh.avif', 'Fresh', 'Unisex', 'Limón, Naranja Dulce, Mandarina, Bergamota', 'Flor de Naranja, Notas Marinas, Jengibre', 'Té, Almizcle, Ámbar'),
('Odyssey Aqua', 'Armaf', 'Fragancia amaderada aromática fresca para hombres de 2023. Aventura y naturaleza encapsuladas en una fragancia fresca y vigorizante con naranja, pachulí y ambroxan.', '/images/armaf/odyssey/aqua.avif', 'Fresh', 'Men', 'Naranja, Pomelo, Artemisia', 'Menta, Lavanda', 'Ambroxan, Pachulí, Ciprés'),
('Odyssey Homme White Edition', 'Armaf', 'Fragancia oriental fougere amaderada para hombres. Fresca, cremosa y cálida con cítricos luminosos sobre una base de ámbar y maderas. Muy cercana a Sauvage While You Sleep.', '/images/armaf/odyssey/homme-white.avif', 'Woody', 'Men', 'Pimienta Rosa, Pomelo, Yuzu', 'Hoja de Violeta, Notas Marinas', 'Ámbar, Amberwood, Madera de Guayaco'),
('Odyssey Dubai Chocolat', 'Armaf', 'Gourmand oriental inspirado en el chocolate de Dubai de 2025. Abre con café, pistacho y knafeh y evoluciona a chocolate, vainilla y cardamomo sobre caramelo y tonka.', '/images/armaf/odyssey/dubai-chocolat.avif', 'Oriental', 'Unisex', 'Café, Pistacho, Avellana, Praliné, Knafeh', 'Chocolate, Vainilla, Cardamomo', 'Caramelo, Haba Tonka, Amberwood'),
('Odyssey Candee', 'Armaf', 'Fragancia frutal gourmand para mujeres de 2024. Fresa, frambuesa y melocotón abren camino a un corazón de caramelo y jazmín sobre una base de pachulí y ámbar.', '/images/armaf/odyssey/candee.avif', 'Floral', 'Women', 'Fresa, Frambuesa, Geranio, Melocotón, Bergamota', 'Caramelo, Jazmín, Maracuyá', 'Pachulí, Almizcle, Ámbar'),
('Odyssey Aoud', 'Armaf', 'Fragancia amaderada especiada para hombres de 2023. Especiada y profunda con azafrán, nuez moscada y lavanda sobre oud y un fondo de ambroxan y pachulí.', '/images/armaf/odyssey/aoud.avif', 'Woody', 'Men', 'Azafrán, Nuez Moscada, Lavanda', 'Oud, Notas Amaderadas', 'Ambroxan, Almizcle, Pachulí'),
('Odyssey Homme', 'Armaf', 'Fragancia oriental clásica para hombres. Cálida y especiada con vainilla y ámbar en la apertura, especias e iris en el corazón y una base de cuero y jazmín. Muy cercana a Tom Ford Noir Extreme.', '/images/armaf/odyssey/homme.avif', 'Oriental', 'Men', 'Vainilla, Ámbar', 'Notas Orientales, Especias, Iris', 'Vainilla, Cuero, Jazmín'),
('Odyssey Wild One', 'Armaf', 'Fragancia amaderada especiada de 2023. Fusión de Versace Dylan Blue y Dior Sauvage. Pimienta, bergamota y menta abren camino a un corazón aromático y una base de maderas y almizcle.', '/images/armaf/odyssey/wild-one.avif', 'Woody', 'Men', 'Pimienta, Bergamota, Limón, Menta', 'Pimienta Rosa, Lavanda, Jengibre, Vetiver', 'Cedro, Pachulí, Elemi, Sándalo, Almizcle, Vetiver'),

-- CLUB DE NUIT LINE
('Club de Nuit Precieux IV', 'Armaf', 'Fragancia floral frutal gourmand para mujeres de 2025. Sal marina, bergamota y manzana abren a un corazón de frutos rojos y flores blancas con una base cremosa de nata y vainilla.', '/images/armaf/club-de-nuit/precieux-iv.avif', 'Floral', 'Women', 'Sal Marina, Bergamota, Manzana', 'Frutos Rojos, Ylang Ylang, Lirio Blanco, Jazmín', 'Nata Montada, Almizcle, Haba Tonka, Pachulí, Vainilla'),
('Club de Nuit Bling', 'Armaf', 'Fragancia woody aromática unisex de 2025. Bold y radiante, captura la esencia del lujo moderno con cítricos, florales y una base de maderas y vainilla.', '/images/armaf/club-de-nuit/bling.avif', 'Woody', 'Unisex', 'Cítricos', 'Flower Prism, Stardust', 'Maderas Aterciopeladas, Vainilla'),
('Club de Nuit Maleka', 'Armaf', 'Fragancia floral frutal para mujeres de 2025, creada por Olivier Cresp. Lychee, bergamota y pimienta rosa abren a un corazón de iris con una base de praliné, ambroxan y sándalo.', '/images/armaf/club-de-nuit/maleka.avif', 'Floral', 'Women', 'Lychee, Bergamota, Pimienta Rosa', 'Iris', 'Praliné, Ambroxan, Sándalo'),
('Club de Nuit Iconic', 'Armaf', 'Fragancia oriental amaderada para hombres. Apertura de pomelo, pimienta rosa y limón con menta y cilantro, corazón de melón y jazmín, base densa de incienso, cedro y ámbar.', '/images/armaf/club-de-nuit/blue-iconic.avif', 'Woody', 'Men', 'Pomelo, Pimienta Rosa, Limón, Menta, Cilantro', 'Melón, Jengibre, Jazmín, Nuez Moscada', 'Incienso, Notas Amaderadas, Cedro, Ámbar, Sándalo, Pachulí, Labdanum'),
('Club de Nuit Untold', 'Armaf', 'Fragancia unisex de 2022. Inspirada en Baccarat Rouge 540. Azafrán y jazmín abren a un corazón de amberwood y ámbar gris con una base de resina de abeto y cedro. Dulce, salada y metálica.', '/images/armaf/club-de-nuit/untold.avif', 'Oriental', 'Unisex', 'Azafrán, Jazmín', 'Amberwood, Ámbar Gris', 'Resina de Abeto, Cedro'),
('Club de Nuit Imperiale', 'Armaf', 'Fragancia floral para mujeres de 2022. Inspirada en Parfums de Marly Delina. Lychee, bergamota y nuez moscada sobre un corazón de rosa turca, peonía y vainilla con base de incienso y cedro.', '/images/armaf/club-de-nuit/imperiale.avif', 'Floral', 'Women', 'Lychee, Bergamota, Nuez Moscada', 'Rosa Turca, Vainilla, Almizcle, Peonía', 'Vainilla, Incienso, Cashmeran, Cedro'),
('Club de Nuit Urban Elixir', 'Armaf', 'Fragancia masculina de 2022 inspirada en Dior Sauvage. Bergamota, pimienta rosa y jazmín abren a un corazón aromático de lavanda y vetiver con una base de ambroxan y ámbar.', '/images/armaf/club-de-nuit/urban-man-elixir.avif', 'Woody', 'Men', 'Bergamota, Pimienta Rosa, Flor de Naranja, Jazmín', 'Lavanda, Elemi, Geranio, Vetiver, Azafrán, Caléndula', 'Ambroxan, Ámbar, Cedro, Pachulí, Labdanum'),
('Club de Nuit Intense Man', 'Armaf', 'El icónico dupe de Creed Aventus de 2015. Apertura de limón, piña y frutas negras, corazón de abedul y jazmín, base profunda de ámbar gris, almizcle y pachulí. Beast mode performer.', '/images/armaf/club-de-nuit/intense-man.avif', 'Woody', 'Men', 'Limón, Piña, Bergamota, Grosella Negra, Manzana', 'Abedul, Jazmín, Rosa', 'Almizcle, Ámbar Gris, Pachulí, Vainilla'),
('Club de Nuit Woman', 'Armaf', 'El clásico dupe de Chanel Coco Mademoiselle para mujeres. Apertura cítrica de naranja y melocotón, corazón floral de rosa y jazmín, base de pachulí, almizcle y vetiver.', '/images/armaf/club-de-nuit/woman.avif', 'Floral', 'Women', 'Naranja, Bergamota, Pomelo, Melocotón', 'Rosa, Jazmín, Geranio, Lychee', 'Pachulí, Almizcle, Vainilla, Vetiver'),

-- MISS ARMAF LINE
('Miss Armaf Magnifiq', 'Armaf', 'Fragancia floral cítrica para mujeres de 2023. Inspirada en Chanel Coco Mademoiselle. Apertura de mandarina y bergamota, corazón de rosa y jazmín, base de pachulí y tonka.', '/images/armaf/miss/magnifiq.avif', 'Floral', 'Women', 'Naranja Mandarina, Naranja, Bergamota', 'Rosa, Jazmín, Mimosa, Ylang-Ylang', 'Almizcle, Pachulí, Vainilla, Vetiver, Tonka'),
('Miss Armaf Voce Viva', 'Armaf', 'Fragancia vibrante y floral para mujeres. Flor de naranja, jazmín y melocotón abren a un corazón de tuberosa, rosa y maracuyá con una base cálida de sándalo y ámbar.', '/images/armaf/miss/voce-viva.avif', 'Floral', 'Women', 'Flor de Naranja, Jazmín, Melocotón', 'Tuberosa, Rosa, Maracuyá', 'Almizcle, Sándalo, Praliné, Ámbar'),
('Miss Armaf Grandeur', 'Armaf', 'Fragancia floral elegante para mujeres de 2023. Bergamota, rosa y florales abren a un corazón de melocotón y frutas con una base de vetiver y ámbar. Opulenta y duradera.', '/images/armaf/miss/grandeur.avif', 'Floral', 'Women', 'Bergamota, Rosa, Florales', 'Melocotón, Notas Frutales', 'Vetiver, Ámbar, Vainilla, Almizcle'),
('Miss Armaf Mystique', 'Armaf', 'Fragancia frutal oriental seductora para mujeres de 2023. Inspirada en Lancome La Nuit Tresor. Frutas y bayas abren a un corazón de rosa y vainilla con una base de café y pachulí.', '/images/armaf/miss/mystique.avif', 'Oriental', 'Women', 'Pera, Mandarina, Bergamota, Naranja', 'Vainilla, Fresa, Mimosa, Rosa, Ylang-Ylang, Jazmín, Maracuyá', 'Vainilla, Café, Haba Tonka, Pachulí, Vetiver'),
('Miss Armaf Dazzling', 'Armaf', 'Fragancia floral glamurosa para mujeres de 2023. Rosa, pera y piña abren a un corazón de jazmín, gardenia y pimienta rosa con una base cálida de vainilla, ámbar y sándalo.', '/images/armaf/miss/dazzling.avif', 'Floral', 'Women', 'Rosa, Pera, Piña, Cítricos, Bergamota', 'Jazmín, Gardenia, Pimienta Rosa', 'Vainilla, Vetiver, Ámbar, Sándalo, Pachulí'),
('Miss Armaf Catwalk', 'Armaf', 'Fragancia floral fresca para mujeres de 2023. Inspirada en Carolina Herrera Good Girl Légère. Cítricos y mandarina abren a un corazón de melocotón, jazmín y lirio con base de vainilla y ambroxan.', '/images/armaf/miss/catwalk.avif', 'Floral', 'Women', 'Mandarina, Naranja, Cítricos', 'Melocotón, Jazmín, Lirio', 'Vainilla, Almizcle, Ambroxan'),
('Miss Armaf Chic', 'Armaf', 'Fragancia frutal floral para mujeres de 2023. Inspirada en YSL Mon Paris. Frambuesa, fresa y pera abren a un corazón de peonía y flor de naranja con una base de pachulí y vainilla.', '/images/armaf/miss/chic.avif', 'Floral', 'Women', 'Frambuesa, Calone, Naranja, Mandarina, Bergamota, Fresa, Pera', 'Peonía, Jazmín, Flor de Naranja', 'Pachulí, Almizcle, Ambroxan, Cedro, Vainilla, Musgo'),

-- TAG LINE
('Tag Her Donna Colorata', 'Armaf', 'Fragancia oriental floral para mujer lanzada en 2024. Tiene una salida luminosa y afrutada con petitgrain, grosella negra y mandarina, seguida de un corazón floral elegante de flor de azahar, jazmín y lavanda. La base combina vainilla, ámbar gris, almizcle y cedro para un acabado suave, femenino y envolvente.', '/images/armaf/tag/donna-colorata.avif', 'Oriental', 'Women', 'Petitgrain, Grosella negra, Mandarina', 'Flor de azahar, Jazmín, Lavanda', 'Vainilla, Ámbar gris, Almizcle, Cedro'),
('Tag Her Donna Di Terra', 'Armaf', 'Fragancia floral para mujer lanzada en 2024. Su apertura mezcla pimienta rosa y cítricos, con un corazón dominado por rosa y notas especiadas. El fondo de pachulí le aporta un carácter terroso, elegante y ligeramente cálido.', '/images/armaf/tag/donna-di-terra.avif', 'Floral', 'Women', 'Pimienta rosa, Cítricos', 'Rosa, Notas especiadas', 'Pachulí'),
('Tag Him Uomo Nero', 'Armaf', 'Fragancia amaderada aromática para hombre lanzada en 2024. Abre con bergamota, pimienta negra, lavanda, cilantro y limón, pasa a un corazón floral-aromático de lirio de los valles, hoja de violeta y rosa, y termina con una base de pachulí, ámbar gris y vainilla. Tiene un perfil masculino, fresco y especiado con fondo cálido.', '/images/armaf/tag/uomo-nero.avif', 'Woody', 'Men', 'Bergamota, Pimienta negra, Lavanda, Cilantro, Limón', 'Lirio de los valles, Hoja de violeta, Rosa', 'Pachulí, Ámbar gris, Vainilla'),

-- OTROS ARMAF
('Nomad Pour Homme', 'Armaf', 'Fragancia frutal amaderada para hombres de 2022. Compleja pirámide de frutas, flores y maderas exóticas con un fondo de cuero y ámbar. Masculina y aventurera.', '/images/armaf/otros/nomad-pour-homme.avif', 'Woody', 'Men', 'Ciruela, Manzana, Frambuesa, Lima, Magnolia, Jengibre, Azafrán, Bergamota', 'Iris, Magnolia, Jazmín, Lirio de los Valles, Geranio', 'Almizcle, Bálsamo de Gurján, Pachulí, Labdanum, Madera de Guayaco, Sándalo, Ámbar, Cuero'),
('Caballo Pour Homme', 'Armaf', 'Fragancia cítrica amaderada para hombres de 2022. Pomelo brillante y bergamota abren a un corazón de jengibre y violeta con una base limpia de ambroxan y vetiver.', '/images/armaf/otros/caballo-pour-homme.avif', 'Fresh', 'Men', 'Pomelo, Limón, Bergamota', 'Jengibre, Ambrette, Violeta', 'Ambroxan, Almizcle, Vetiver, Pachulí'),
('Ventana Pour Homme', 'Armaf', 'Fragancia amaderada aromática para hombres de 2017. El gran dupe de Dior Sauvage EDT. Apertura cítrica de pomelo y mandarina, corazón de lavanda y geranio, base de cedro y ámbar.', '/images/armaf/otros/ventana-pour-homme.avif', 'Woody', 'Men', 'Pomelo, Limón, Mandarina', 'Lavanda, Geranio, Vetiver, Pachulí', 'Cedro, Ámbar, Maderas Preciosas');


-- VOLARÉ
INSERT INTO perfumes (name, brand, description, image_url, fragrance_family, gender, top_notes, middle_notes, base_notes) VALUES
('Esta Puro', 'Volaré', 'Dupe de Xerjoff Erba Pura. Apertura cítrica mediterránea con almizcle cremoso y base cálida de vainilla y ámbar.', '/images/volare/xerjoff/esta-puro.avif', 'Oriental', 'Unisex', 'Naranja Siciliana, Limón, Bergamota', 'Almizcle', 'Ámbar, Vainilla, Almizcle Blanco'),
('Asgardian II', 'Volaré', 'Dupe de Xerjoff Alexandria II. Fragancia oriental sofisticada con lavanda, especias y una base rica en oud y vainilla.', '/images/volare/xerjoff/asgardian-ii.avif', 'Oriental', 'Unisex', 'Lavanda, Manzana Verde, Canela', 'Jazmín, Violeta, Lirio de los Valles', 'Oud, Vainilla, Almizcle Blanco'),
('Esta Oro', 'Volaré', 'Versión más cálida y especiada de Esta Puro con un perfil más intenso y envolvente.', '/images/volare/xerjoff/eseta-oro.avif', 'Oriental', 'Unisex', 'Limón, Naranja, Bergamota, Jengibre', 'Cardamomo, Canela, Clavo', 'Ámbar, Vainilla, Almizcle'),
('Mexican Bronco', 'Volaré', 'Dupe de Xerjoff Naxos. Fragancia intensa con apertura aromática y fondo cálido ambarado.', '/images/volare/xerjoff/mexican-bronco.avif', 'Oriental', 'Men', 'Bergamota, Elemí, Ajenjo', 'Lavanda, Cardamomo, Cuero', 'Ámbar, Cedro, Pachulí'),
('Milano 22', 'Volaré', 'Dupe de Xerjoff Torino 22. Fragancia fresca y elegante con perfil aromático mediterráneo.', '/images/volare/xerjoff/milano22.png', 'Fresh', 'Unisex', 'Menta, Limón, Albahaca', 'Grosella Negra, Lavanda, Jazmín', 'Almizcle, Verbena'),
('Above the Clouds', 'Volaré', 'Fragancia fresca y luminosa con salida cítrica, corazón especiado y fondo ambarado suave.', '/images/volare/lv/above-the-clouds.avif', 'Fresh', 'Unisex', 'Notas cítricas', 'Notas especiadas', 'Ámbar, Almizcle'),
('Amazon Rainfall', 'Volaré', 'Fragancia verde acuática inspirada en la selva tropical. Fresca, natural y muy limpia.', '/images/volare/lv/amazon-rainfall.avif', 'Fresh', 'Unisex', 'Limón, Naranja, Notas verdes', 'Romero, Jazmín, Rosa', 'Almizcle, Vetiver, Musgo'),
('Golden Hour', 'Volaré', 'Fragancia cítrica floral con un perfil luminoso y cálido inspirado en el atardecer.', '/images/volare/lv/golden-hour.avif', 'Fresh', 'Unisex', 'Lima, Mandarina, Bergamota', 'Flor de tiaré', 'Sándalo, Almizcle'),
('Luminous Waves', 'Volaré', 'Fragancia acuática aromática inspirada en L’Immensité. Muy fresca, limpia y elegante.', '/images/volare/lv/luminous-waves.avif', 'Fresh', 'Men', 'Pomelo, Jengibre, Bergamota', 'Notas acuáticas, Romero, Salvia', 'Ambroxan, Ámbar'),
('Valerio Uomo Intense', 'Volaré', 'Dupe de Valentino Uomo Intense. Fragancia cálida con cuero, pachulí y vainilla.', '/images/volare/valentino/valerio-uomo-intense.png', 'Oriental', 'Men', 'Pachulí', 'Cuero', 'Haba tonka'),
('Valerio Donna Born To Win', 'Volaré', 'Fragancia floral ambarada vainillada para mujer inspirada en Valentino Donna Born In Roma. Se abre con un bouquet luminoso de jazmín sambac que aporta elegancia y feminidad. En el corazón, los acordes ambarados y el cashmeran crean una sensación cálida, cremosa y envolvente. La base de vainilla bourbon aporta profundidad y una estela dulce, sofisticada y altamente adictiva.', '/images/volare/valentino/valerio-donna-born-to-win.png', 'Floral', 'Women', 'Jazmín, Jazmín Sambac', 'Acorde ambarado, Cashmeran', 'Vainilla Bourbon');


-- FRENCH AVENUE
INSERT INTO perfumes (name, brand, description, image_url, fragrance_family, gender, top_notes, middle_notes, base_notes) VALUES
('Liquid Brun', 'French Avenue', 'Dupe del PDM Althaïr. Una de las mayores sorpresas gourmand de 2024. Apertura especiada de cardamomo, canela, flor de naranja y bergamota. Corazón de vainilla bourbon y elemí resinoso. Base de praliné, ambroxan, madera de guayaco y almizcle. Cálido, adictivo y con performance brutal.', '/images/french-avenue/sweet-pleasure/liquid-brun.avif', 'Oriental', 'Unisex', 'Canela, Flor de Naranja, Cardamomo, Bergamota', 'Vainilla Bourbon, Elemí', 'Praliné, Ambroxan, Madera de Guayaco, Almizcle'),
('Liquid Brun Limited Edition', 'French Avenue', 'Versión extrait de parfum del aclamado Liquid Brun. Más cálida y compleja con notas de rosa turca y madera que añaden profundidad. Base de vainilla cremosa y chocolate. La versión definitiva del DNA de Althaïr. Absolutamente adictiva.', '/images/french-avenue/sweet-pleasure/liquid-brun-limited-edition.avif', 'Oriental', 'Unisex', 'Flor de Naranja, Cardamomo, Canela', 'Rosa Turca, Vainilla, Chocolate', 'Madera, Almizcle, Ámbar'),
('Sweet Paradise', 'French Avenue', 'Fragancia floral frutal para mujeres de 2024. Creada por Carole Calmettes. Apertura de ambrette, almizcle y mandarina. Corazón cremoso y suave con notas lácteas. Base de haba tonka. Delicada, femenina y envolvente como una loción de lujo.', '/images/french-avenue/sweet-pleasure/sweet-paradise.avif', 'Floral', 'Women', 'Ambrette, Almizcle, Mandarina', 'Notas Lácteas, Melocotón, Iris', 'Haba Tonka, Almizcle Blanco'),
('Meringue', 'French Avenue', 'Fragancia floral frutal para mujeres de 2024. Creada por Carole Calmettes. Apertura de piña, mandarina y bergamota que evoluciona a un corazón floral cremoso con base de notas dulces y suaves. Juguetona, fresca y adictiva.', '/images/french-avenue/sweet-pleasure/meringue.avif', 'Floral', 'Women', 'Piña, Mandarina, Bergamota', 'Florales Cremosas, Jazmín', 'Almizcle, Vainilla, Haba Tonka'),
('Chocola Addict', 'French Avenue', 'Fragancia gourmand oriental unisex de 2025. Apertura de chocolate, mandarina y ámbar. Corazón inesperado de cuero e incienso que añade profundidad y misterio. Base de vainilla y mirra. Seductora, sofisticada y polarizante.', '/images/french-avenue/otros/chocola-addict.avif', 'Oriental', 'Unisex', 'Chocolate, Mandarina, Ámbar', 'Cuero, Incienso', 'Vainilla, Mirra'),
('Eclair Affair', 'French Avenue', 'Fragancia gourmand unisex inspirada en Bianco Latte. Caramelo cremoso, coco y haba tonka abren a un corazón suave y dulce. Base ahumada y cálida. Más suave y menos estridente que el Eclaire de Lattafa. Adictiva y cómoda.', '/images/french-avenue/otros/eclair-affair.avif', 'Oriental', 'Unisex', 'Caramelo, Bergamota', 'Coco, Pralinée, Jazmín', 'Haba Tonka, Almizcle, Vainilla'),
('Coconut Leche', 'French Avenue', 'Fragancia floral oriental para mujeres de 2025. Creada por Meabh McCurtin. Nota principal de coco tostado que evoluciona a tuberosa cremosa. Base suave de vainilla y benzoin. Como un rafaello líquido con un toque floral maduro. Irresistible y adictiva.', '/images/french-avenue/otros/coconut-leche.avif', 'Floral', 'Women', 'Coco', 'Tuberosa', 'Vainilla, Benzoin'),
('Mythical Gryphon', 'French Avenue', 'Fragancia oriental especiada para hombres de 2025. Apertura de bergamota, azafrán, pimienta y cardamomo. Corazón de cedro, Akigalawood, canela y rosa. Base de pachulí, vetiver, vainilla y ámbar seco. Poderoso, misterioso y con una botella espectacular.', '/images/french-avenue/otros/mythical-gryphon.avif', 'Oriental', 'Men', 'Bergamota, Azafrán, Pimienta, Cardamomo', 'Cedro, Akigalawood, Canela, Rosa', 'Pachulí, Vetiver, Vainilla, Ámbar Seco'),
('Venus de Milo', 'French Avenue', 'Fragancia oriental vainilla para mujeres de 2025. Apertura gourmand de naranja, pera y caramelo dorado. Corazón de flores blancas, lirio de los valles y jazmín cremoso con acorde lácteo. Base de vainilla de Madagascar, ambroxan, benzoin y almizcle suave. Etérea, femenina y absolutamente adictiva.', '/images/french-avenue/otros/venus-de-milo.avif', 'Oriental', 'Women', 'Naranja, Pera, Caramelo Dorado', 'Flores Blancas, Lirio de los Valles, Jazmín, Acorde Lácteo', 'Vainilla de Madagascar, Ambroxan, Benzoin, Almizcle'),
('Spectre Ghost', 'French Avenue', 'Dupe de YSL Y EDP para hombres lanzado en 2023. Apertura de jengibre, cardamomo y bergamota. Corazón de pimienta rosa, grosella negra y rosa. Base de notas amaderadas y almizcle.', '/images/french-avenue/spectre/ghost.avif', 'Woody', 'Men', 'Jengibre, Cardamomo, Bergamota', 'Pimienta Rosa, Grosella Negra, Rosa', 'Notas Amaderadas, Almizcle, Cedro'),
('Lumiere Elle', 'French Avenue', 'Fragancia floral oriental para mujeres y hombres de 2024. Apertura fresca de jengibre, mandarina y pera. Corazón de flor de naranjo, rosa y jazmín. Base de ámbar gris, pimienta peruana y sándalo.', '/images/french-avenue/lumiere/elle.avif', 'Floral', 'Unisex', 'Jengibre, Mandarina, Pera', 'Flor de naranjo, Rosa, Jazmín', 'Ámbar gris, Pimienta peruana, Sándalo'),
('Vulcan Feu', 'French Avenue', 'Fragancia floral frutal unisex de 2025. Apertura vibrante de mango, limón, jengibre y ruibarbo. Corazón de pimienta rosa, jazmín, violeta y praliné. Base de haba tonka, cedro, ámbar gris y musgo.', '/images/french-avenue/vulcan/feu.avif', 'Floral', 'Unisex', 'Mango, Limón, Jengibre, Ruibarbo', 'Pimienta Rosa, Jazmín, Violeta, Praliné', 'Haba Tonka, Cedro, Ámbar Gris, Musgo'),
('Vulcan Baie', 'French Avenue', 'Fragancia frutal floral unisex de 2025. Apertura de grosella negra, mora, romero y bergamota. Corazón de frambuesa, vodka, albahaca y lirio de los valles.', '/images/french-avenue/vulcan/baie.avif', 'Floral', 'Unisex', 'Grosella Negra, Mora, Romero, Bergamota', 'Frambuesa, Vodka, Albahaca, Lirio de los Valles', 'Fresa, Almizcle, Melocotón, Ámbar, Sándalo, Pachulí, Incienso'),
('Vulcan Sable', 'French Avenue', 'Fragancia aromática unisex de 2025. Apertura de whisky, naranja, mandarina y cilantro. Base cálida de tonka, benzoin y cashmeran.', '/images/french-avenue/vulcan/sable.avif', 'Oriental', 'Unisex', 'Whisky, Naranja, Mandarina, Cilantro', 'Especias Cálidas, Madera', 'Haba Tonka, Benzoin, Cashmeran, Vainilla'),
('Royal Blend Vintage', 'French Avenue', 'Fragancia oriental fougere unisex de 2025. Apertura de ciruela y davana. Base cálida y profunda con gran rendimiento.', '/images/french-avenue/royal-blend/vintage.avif', 'Oriental', 'Unisex', 'Ciruela, Davana', 'Especias, Iris', 'Ámbar, Almizcle, Notas Amaderadas');


-- PARIS CORNER
INSERT INTO perfumes (name, brand, description, image_url, fragrance_family, gender, top_notes, middle_notes, base_notes) VALUES
('Khair Pistachio', 'Paris Corner', 'Dupe de Kayali Yum Pistachio Gelato. Apertura de bergamota, pistacho gelato y ron dulce. Corazón de geranio, peonía blanca, jazmín y frambuesa. Base cremosa de nata montada, malvavisco, cacao, cedro y haba tonka. Nuclear performer.', '/images/paris-corner/khair-pistachio.avif', 'Oriental', 'Unisex', 'Bergamota Italiana, Pistacho Gelato, Ron Dulce, Cardamomo, Avellana', 'Geranio, Peonía Blanca, Jazmín, Frambuesa, Melocotón Blanco, Pera', 'Nata Montada, Malvavisco, Algodón de Azúcar, Cacao, Cedro, Sándalo, Haba Tonka'),
('Khair Fusion', 'Paris Corner', 'Dupe de Kayali Eden Sparkling Lychee. Apertura de lychee, manzana roja, grosella negra y limón italiano. Corazón floral de jazmín sambac, rosa Taif y pensamiento. Base de vainilla, almizcle, sándalo y cedro. Frutal, fresco y adictivo.', '/images/paris-corner/khair-fusion.avif', 'Floral', 'Unisex', 'Lychee, Manzana Roja, Grosella Negra, Limón Italiano', 'Jazmín Sambac, Rosa Taif, Pensamiento', 'Vainilla, Almizcle, Sándalo, Cedro'),
('Khair Felicity', 'Paris Corner', 'Dupe de Kayali Wedding Silk Santal. Apertura chispeante de champán, cassis y fresia. Corazón de rosa de mayo, almizcle y jazmín. Base de vainilla, notas dulces y almizcle. Elegante, romántica y adictiva.', '/images/paris-corner/khair-felicity.avif', 'Floral', 'Women', 'Champán, Fresia, Cassis', 'Almizcle, Jazmín, Rosa de Mayo', 'Vainilla, Notas Dulces, Almizcle'),
('Zodiac', 'Paris Corner', 'Fragancia unisex equilibrada entre frescura y calidez oriental de 2024. Apertura de jengibre, pera y bergamota. Corazón de flor de naranja, jazmín y notas amaderadas. Base de ámbar, almizcle y sándalo. Sofisticada y versátil.', '/images/paris-corner/zodiac.avif', 'Oriental', 'Unisex', 'Jengibre, Pera, Bergamota', 'Flor de Naranja, Jazmín, Notas Amaderadas', 'Ámbar, Almizcle, Sándalo'),
('Zodiac Stratos', 'Paris Corner', 'Dupe de YSL Y Elixir de 2024. Apertura frutal fresca con clementina y naranja. Corazón de notas amaderadas, manzana y pimienta negra. Base oscura y elegante de vetiver, ámbar y madera. Cautivador para hombres modernos.', '/images/paris-corner/zodiac-stratos.avif', 'Woody', 'Men', 'Clementina, Naranja, Manzana, Pimienta Negra', 'Notas Amaderadas, Manzana', 'Vetiver, Ámbar, Madera'),
('Voux Elegante', 'Paris Corner', 'Dupe de Xerjoff Naxos. Fragancia oriental especiada unisex de 2024. Lavanda y bergamota abren a un corazón de miel, cashmeran, canela y jazmín. Base de vainilla, tabaco y haba tonka. Cálida, seductora y muy duradera.', '/images/paris-corner/voux-elegante.avif', 'Oriental', 'Unisex', 'Lavanda, Bergamota', 'Miel, Cashmeran, Canela, Jazmín', 'Vainilla, Tabaco, Haba Tonka'),
('Voux Zingy', 'Paris Corner', 'Dupe de Xerjoff Torino 21. Fragancia cítrica aromática unisex de 2025. Apertura refrescante de albahaca, limón, bergamota y cidro. Corazón de verbena, jazmín y ambretolida. Base limpia de almizcle. Perfecta para verano.', '/images/paris-corner/voux-zingy.avif', 'Fresh', 'Unisex', 'Albahaca, Limón, Bergamota, Cidro', 'Verbena, Jazmín, Ambretolida', 'Almizcle'),
('Voux Turquoise', 'Paris Corner', 'Dupe de Xerjoff Erba Pura con toque tropical. Unisex de 2024. Apertura de naranja siciliana, bergamota calabresa y limón siciliano. Corazón frutal tropical de mango, piña y melón. Base de vainilla de Madagascar, almizcle blanco y ámbar.', '/images/paris-corner/voux-turquoise.avif', 'Oriental', 'Unisex', 'Naranja Siciliana, Bergamota Calabresa, Limón Siciliano', 'Notas Frutales Tropicales', 'Vainilla de Madagascar, Almizcle Blanco, Ámbar'),
('Voux Patisserie', 'Paris Corner', 'Inspirada en Xerjoff Italica. Fragancia floral frutal gourmand unisex de 2024. Cardamomo, mandarina y azafrán abren a un corazón de manzana y rosa. Base de vainilla y sándalo. Especiada, frutal y gourmand con carácter.', '/images/paris-corner/voux-patisserie.avif', 'Floral', 'Unisex', 'Cardamomo, Mandarina, Azafrán', 'Manzana, Rosa', 'Vainilla, Sándalo'),
('Voux Violette', 'Paris Corner', 'Fragancia floral frutal unisex de 2022. Apertura de piña e jacinto. Corazón de iris, pimienta rosa y jazmín. Base de almizcle, vainilla, pachulí, ámbar y vetiver. Fresca y versátil para todo el año.', '/images/paris-corner/voux-violette.avif', 'Floral', 'Unisex', 'Piña, Jacinto', 'Iris, Pimienta Rosa, Jazmín', 'Almizcle, Vainilla, Pachulí, Ámbar, Vetiver'),
('Reham Vanilla Mood', 'Paris Corner', 'Fragancia oriental vainilla unisex de 2025. Apertura de ambrette, notas ozónicas y jengibre. Corazón de mirra, benzoin e iris. Base de vainilla, cuero y almizcle. Cálida, envolvente y seductora.', '/images/paris-corner/reham-vanilla-mood.avif', 'Oriental', 'Unisex', 'Ambrette, Notas Ozónicas, Jengibre', 'Mirra, Benzoin, Iris', 'Vainilla, Cuero, Almizcle'),
('Reham Wild Mineral', 'Paris Corner', 'Fragancia acuática frutal unisex de 2025. Apertura de kiwi, pimienta rosa y melocotón. Corazón de notas marinas, loto y sándalo. Base de ámbar gris, azúcar y musgo de roble. Evoca la naturaleza costera salvaje.', '/images/paris-corner/reham-wild-mineral.avif', 'Fresh', 'Unisex', 'Kiwi, Pimienta Rosa, Melocotón', 'Notas Marinas, Loto, Sándalo', 'Ámbar Gris, Azúcar, Musgo de Roble'),
('Reham Rose Petals', 'Paris Corner', 'Fragancia floral frutal unisex de 2025. Apertura de lychee, frambuesa y bergamota. Corazón de rosa, notas acuáticas y madera de cachemir. Base de notas dulces, ámbar, almizcle y sándalo. Equilibrada entre frescura y calidez.', '/images/paris-corner/reham-rose-petals.avif', 'Floral', 'Unisex', 'Lychee, Frambuesa, Bergamota', 'Rosa, Notas Acuáticas, Madera de Cachemir', 'Notas Dulces, Ámbar, Almizcle, Sándalo'),
('Taskeen Caramel Cascade', 'Paris Corner', 'Fragancia oriental gourmand unisex. Apertura cálida y especiada de caramelo y dátiles. Corazón cremoso de vainilla y notas orientales. Base profunda de ámbar, almizcle y madera. Confortante y adictiva.', '/images/paris-corner/taskeen-caramel-cascade.avif', 'Oriental', 'Unisex', 'Caramelo, Dátiles, Especias', 'Vainilla, Notas Orientales', 'Ámbar, Almizcle, Madera'),
('Taskeen Lactéa Divina', 'Paris Corner', 'Dupe de Juliette Has a Gun Blanche Bête. Fragancia floral unisex de 2024. Apertura de cacao e incienso. Corazón de tuberosa y jazmín. Base de leche, vainilla y haba tonka. Cremosa, etérea y absolutamente adictiva.', '/images/paris-corner/taskeen-lactea-divina.avif', 'Floral', 'Unisex', 'Cacao, Incienso', 'Tuberosa, Jazmín', 'Leche, Vainilla, Haba Tonka'),
('Taskeen Marina', 'Paris Corner', 'Fragancia fresca frutal unisex inspirada en Delina La Rose. Perfil luminoso y limpio centrado en pomelo, grosella negra y lirio de los valles.', '/images/paris-corner/taskeen-marina.avif', 'Fresh', 'Unisex', 'Pomelo, Grosella negra', 'Lirio de los valles', NULL),
('Taskeen', 'Paris Corner', 'Fragancia oriental para hombres y mujeres. Apertura de melocotón, naranja sanguina y cardamomo. Corazón de heliotropo, davana, coñac y jazmín. Base de sándalo, benzoin, cashmeran, vainilla, haba tonka, labdanum y pachulí. Opulenta y sofisticada.', '/images/paris-corner/taskeen.avif', 'Oriental', 'Unisex', 'Melocotón, Naranja Sanguina, Cardamomo', 'Heliotropo, Davana, Coñac, Jazmín', 'Sándalo, Benzoin, Cashmeran, Vainilla, Haba Tonka, Labdanum, Pachulí'),
('Oud Holidays', 'Paris Corner', 'Fragancia oriental amaderada unisex de 2024. Apertura de bergamota, limón y tabaco. Corazón de oud, especias y notas amaderadas. Base profunda de ámbar y almizcle. Cálida, refinada y perfecta para ocasiones especiales.', '/images/paris-corner/oud-holidays.avif', 'Oriental', 'Unisex', 'Bergamota, Limón, Tabaco', 'Oud, Especias, Notas Amaderadas', 'Ámbar, Almizcle, Sándalo'),
('Virilis', 'Paris Corner', 'Fragancia oriental fougere para hombres de 2024. Apertura de lavanda, menta, piña, artemisia, canela y bergamota. Corazón de ámbar, amberwood, benzoin y pachulí. Base de vainilla, toffee, musgo de roble y almizcle. Bold y masculino.', '/images/paris-corner/virilis.avif', 'Oriental', 'Men', 'Lavanda, Menta, Piña, Artemisia, Canela, Bergamota', 'Ámbar, Amberwood, Benzoin, Pachulí', 'Vainilla, Toffee, Musgo de Roble, Almizcle'),
('Gladiators Oath', 'Paris Corner', 'Fragancia oriental amaderada para hombres de la línea Ministry of Oud. Poderosa y audaz con especias orientales, oud y una base profunda de cuero y ámbar. Para hombres que buscan una presencia imponente e indomable.', '/images/paris-corner/gladiators-oath.avif', 'Oriental', 'Men', 'Azafrán, Especias, Bergamota', 'Oud, Incienso, Notas Amaderadas', 'Cuero, Ámbar, Almizcle, Vetiver'),
('Marshmallow Blush', 'Paris Corner', 'Dupe de Kayali Yum Bougie Marshmallow. Fragancia frutal gourmand unisex de 2025. Apertura de fresa y notas cítricas. Corazón de malvavisco y flor de naranja. Base cremosa de vainilla y almizcle. Como un batido de fresa y malvavisco en botella.', '/images/paris-corner/marshmallow-blush.avif', 'Floral', 'Unisex', 'Fresa, Notas Cítricas', 'Malvavisco, Flor de Naranja', 'Vainilla, Almizcle'),
('Indomitable', 'Paris Corner', 'Fragancia unisex de abril 2025. Apertura radiante de clementina y naranja madura al sol. Corazón de notas amaderadas, manzana y pimienta negra. Base cálida y elegante. Tropical, fresca y con un toque exótico de mango verde.', '/images/paris-corner/indomitable.avif', 'Fresh', 'Unisex', 'Clementina, Naranja, Manzana, Pimienta Negra', 'Notas Amaderadas, Manzana', 'Ámbar, Almizcle, Madera'),
('Rua', 'Paris Corner', 'Fragancia floral frutal gourmand para mujeres de 2024. Apertura de ruibarbo, cítricos y rosa. Corazón de frambuesa, magnolia, vainilla y melocotón. Base de amberwood, caramelo y almizcle. Romántica, dulce y muy femenina.', '/images/paris-corner/rua.avif', 'Floral', 'Women', 'Ruibarbo, Cítricos, Rosa', 'Frambuesa, Magnolia, Vainilla, Melocotón', 'Amberwood, Caramelo, Almizcle'),
('Rifaaqat', 'Paris Corner', 'Fragancia oriental unisex de la colección Taskeen. Cálida y especiada con notas de oud, rosas y ámbar sobre una base de almizcle. Evoca la amistad y la conexión entre almas. Envolvente y memorable.', '/images/paris-corner/rifaaqat.avif', 'Oriental', 'Unisex', 'Especias, Bergamota, Rosa', 'Oud, Notas Orientales', 'Ámbar, Almizcle, Madera'),
('Hurriya', 'Paris Corner', 'Fragancia oriental amaderada unisex de 2025. Apertura de cuero, maracuyá y bergamota. Corazón de oud, labdanum y rosa. Base de benzoin, pachulí y almizcle. Sofisticada, audaz y perfecta para veladas especiales.', '/images/paris-corner/hurriya.avif', 'Oriental', 'Unisex', 'Cuero, Maracuyá, Bergamota', 'Oud, Labdanum, Rosa', 'Benzoin, Pachulí, Almizcle'),
('Date Caramel', 'Paris Corner', 'Fragancia oriental gourmand unisex de 2025. Combina la dulzura dorada de los dátiles con caramelo y un toque de café. Envuelta en la calidez de la vainilla y el ámbar. Base profunda y sedosa. Nuclear performer con estela bestial.', '/images/paris-corner/date-caramel.avif', 'Oriental', 'Unisex', 'Dátiles, Caramelo, Café', 'Vainilla, Especias Cálidas', 'Ámbar, Almizcle, Sándalo, Benzoin'),
('Mango Punch', 'Paris Corner', 'Fragancia frutal unisex de 2025. Apertura vibrante de mango, mora y pimienta negra. Corazón de loto e iris. Base de almizcle suave. Jugosa, tropical y refrescante como un punch de mango recién exprimido. Perfecta para verano.', '/images/paris-corner/mango-punch.avif', 'Fresh', 'Unisex', 'Mango, Mora, Pimienta Negra', 'Loto, Iris', 'Almizcle');


-- FRAGRANCE WORLD
INSERT INTO perfumes (name, brand, description, image_url, fragrance_family, gender, top_notes, middle_notes, base_notes) VALUES
('Urban Man Paradise', 'Fragrance World', 'Fragancia aromática acuática inspirada en Le Beau Paradise Garden de Jean Paul Gaultier. Abre con notas acuáticas, verdes, menta y jengibre vigorizantes. El corazón revela coco, higo cremoso y notas salinas que evocan la brisa del océano. La base de sándalo y haba tonka aporta calidez y sensualidad.', '/images/fragance-world/urban-man-paradise.png', 'Fresh', 'Men', 'Notas acuáticas, Notas verdes, Menta, Jengibre', 'Coco, Higo, Sal', 'Sándalo, Haba tonka'),
('Neroli Riviera', 'Fragrance World', 'Fragancia cítrica aromática unisex lanzada en 2022, inspirada en Neroli Portofino de Tom Ford. Captura las brisas frescas, el agua cristalina y la exuberante vegetación de la Riviera italiana con aceites cítricos frescos, sorprendentes notas florales y matices ambarinos.', '/images/fragance-world/neroli-riviera.avif', 'Fresh', 'Unisex', 'Naranja amarga, Bergamota, Limón, Mandarina, Lavanda, Mirto, Romero', 'Neroli, Flor de naranjo africana, Jazmín, Pitosporo', 'Almizcle de ambrette, Ámbar, Malva, Angélica'),
('Urban Man Le Parfum', 'Fragrance World', 'Fragancia oriental amaderada inspirada en Le Male Le Parfum de Jean Paul Gaultier. Desde el primer spray cautiva con su composición exclusiva. El cardamomo aporta calidez especiada, la lavanda e iris dan frescura elegante, y la vainilla con notas orientales crea una estela memorable.', '/images/fragance-world/urban-man-le-parfum.png', 'Oriental', 'Men', 'Cardamomo', 'Lavanda, Iris', 'Vainilla, Notas orientales, Notas amaderadas'),
('Just Wardi', 'Fragrance World', 'Fragancia oriental floral lanzada en 2023. Una mezcla lujosa que cautiva los sentidos entrelazando acordes frutales, florales y dulces. El coco cremoso, melocotón y mandarina se funden con flores blancas, rosa e ylang-ylang, sobre una base cálida de vainilla y caramelo.', '/images/fragance-world/just-wardi.avif', 'Oriental Floral', 'Women', 'Coco, Mandarina, Melocotón', 'Notas dulces, Ylang-ylang, Flores blancas, Rosa', 'Vainilla, Caramelo, Almizcle, Ámbar, Cedro'),
('Creme of Clouds', 'Fragrance World', 'Fragancia oriental vainillada unisex lanzada en 2025, inspirada en Crème Brûlée de Theodoros Kalotinis. Una fragancia lujosamente suave y deliciosamente dulce que envuelve en un capullo de coco cremoso, vainilla aterciopelada y azúcar caramelizado. Confort, elegancia e indulgencia.', '/images/fragance-world/creme-of-clouds.avif', 'Oriental Vanilla', 'Unisex', 'Nata montada, Azúcar quemado', 'Leche de coco', 'Vainilla');


-- RASASI HAWAS
INSERT INTO perfumes (name, brand, description, image_url, fragrance_family, gender, top_notes, middle_notes, base_notes) VALUES
('Hawas Atlantis', 'Rasasi', 'Fragancia acuática mineral unisex lanzada en 2025. Inspirada en las profundidades del océano y la leyenda de la Atlántida. Misteriosa, acuática y poderosa.', '/images/rasasi/hawas/atlantis.avif', 'Fresh', 'Unisex', 'Bergamota, Limón, Manzana, Canela', 'Notas acuáticas, Flor de naranjo, Ciruela, Cardamomo', 'Madera flotante, Ámbar gris, Almizcle, Pachulí'),
('Hawas Black', 'Rasasi', 'Fragancia aromática frutal lanzada en 2024. El hermano oscuro de la familia Aventus/Hacivat. La combinación clásica de piña, cítricos y musgo se oscurece con pachulí especiado y maderas carbonizadas. Potente y con gran proyección.', '/images/rasasi/hawas/black.avif', 'Aromatic Fruity', 'Men', 'Bergamota, Pomelo, Piña', 'Pachulí, Cedro, Jazmín', 'Musgo de roble, Notas amaderadas, Ámbar'),
('Hawas Diva', 'Rasasi', 'Fragancia oriental floral lanzada en 2025. Encarna presencia e individualidad. Combina frutas rojas jugosas con un corazón floral de rosa y notas resinosas de incienso, sobre una base cálida de vainilla y ámbar gris.', '/images/rasasi/hawas/diva.avif', 'Floral', 'Women', 'Frutas rojas, Ruibarbo, Lichi', 'Rosa, Cedro, Incienso', 'Vainilla, Almizcle, Ámbar gris'),
('Hawas Elixir', 'Rasasi', 'Fragancia gourmand dulce unisex lanzada en 2024. Seductora y suave, abre con una dulzura rica y jugosa equilibrada con notas frescas acuáticas. Las especias cálidas y matices cremosos con chocolate oscuro y menta añaden profundidad y sensualidad.', '/images/rasasi/hawas/elixir.avif', 'Oriental', 'Unisex', 'Menta, Artemisa, Bergamota', 'Chocolate oscuro, Lavanda', 'Vainilla, Haba tonka, Almizcle'),
('Hawas Fire', 'Rasasi', 'Fragancia unisex lanzada en 2025 que encarna intensidad audaz y elegancia innegable. Captura el espíritu de la pasión y la sofisticación.', '/images/rasasi/hawas/fire.avif', 'Aromatic Aquatic', 'Unisex', 'Salvia esclarea', 'Jazmín egipcio, Notas marinas', 'Ámbar gris, Ámbar, Notas minerales'),
('Hawas for Her', 'Rasasi', 'Fragancia floral lanzada en 2015, creada por Claire Liégent y Dominique Ropion. Combina frescura frutal con florales elegantes y una base gourmand cálida. Versátil y femenina para todo el año.', '/images/rasasi/hawas/for-her.avif', 'Floral', 'Women', 'Granada, Manzana, Pomelo', 'Iris, Jazmín Sambac, Cítricos', 'Praliné, Pachulí, Vetiver'),
('Hawas for Him', 'Rasasi', 'Fragancia aromática acuática lanzada en 2015. La original que inició la colección. Mezcla canela, bergamota, flor de naranjo, ámbar gris y sándalo para crear un aroma acuático que encarna la fuerza y el vigor masculino. Rendimiento bestial.', '/images/rasasi/hawas/for-him.avif', 'Aromatic Aquatic', 'Men', 'Manzana, Bergamota, Limón, Canela', 'Notas acuáticas, Ciruela, Flor de naranjo, Cardamomo', 'Ámbar gris, Almizcle, Pachulí, Madera flotante'),
('Hawas Ice', 'Rasasi', 'Fragancia aromática lanzada en 2023. Versión fresca y revitalizante del Hawas original. Abre con manzana crujiente, limón italiano y bergamota siciliana con un toque de anís estrellado.', '/images/rasasi/hawas/ice.avif', 'Fresh', 'Men', 'Manzana, Limón italiano, Bergamota siciliana, Anís estrellado', 'Ciruela, Flor de naranjo, Cardamomo', 'Almizcle, Ámbar, Madera flotante, Musgo'),
('Hawas Kobra', 'Rasasi', 'Fragancia oriental amaderada lanzada en 2025. Abre con jengibre, bergamota y mandarina creando un efecto fresco y limpio. El té verde y el neroli aportan un carácter herbal auténtico. Base cálida de almizcle, maderas y ámbar.', '/images/rasasi/hawas/kobra.avif', 'Oriental', 'Men', 'Jengibre, Bergamota, Mandarina', 'Canela, Té verde, Neroli', 'Almizcle, Notas amaderadas, Ámbar'),
('Hawas London', 'Rasasi', 'Fragancia oriental amaderada unisex lanzada en 2026. Composición moderna con una apertura fresca y ligeramente especiada y una base cálida amaderada-ambarada. Rosa, incienso y flores blancas en el corazón.', '/images/rasasi/hawas/london.avif', 'Oriental', 'Unisex', 'Pimienta rosa, Azafrán, Pera', 'Rosa, Incienso, Flores blancas', 'Maderas rubias, Ámbar, Almizcle, Vainilla'),
('Hawas Malibu', 'Rasasi', 'Fragancia aromática unisex lanzada en 2025. Inspirada en la costa californiana. Abre con piña, naranja y pomelo vibrantes. El corazón de ámbar, iris y lavanda aporta elegancia, y la base de haba tonka, cashmeran y pachulí ofrece calidez duradera.', '/images/rasasi/hawas/malibu.avif', 'Aromatic', 'Unisex', 'Piña, Naranja, Pomelo', 'Ámbar, Iris, Lavanda', 'Haba tonka, Almizcle, Cashmeran, Pachulí'),
('Hawas Tropical', 'Rasasi', 'Fragancia aromática verde lanzada en 2025. Inspirada en una escapada tropical. Abre con agua de coco, hoja de higuera y jengibre vigorizantes. El corazón de coco, higo y menta ofrece dulzura cremosa. Base cálida de sándalo y haba tonka.', '/images/rasasi/hawas/tropical.avif', 'Aromatic Green', 'Men', 'Agua de coco, Hoja de higuera, Jengibre', 'Coco, Higo, Menta', 'Sándalo, Haba tonka, Almizcle');


-- LATTAFA
INSERT INTO perfumes (name, brand, description, image_url, fragrance_family, gender, top_notes, middle_notes, base_notes) VALUES
('Al Noble Safeer', 'Lattafa', 'Fragancia verde cítrica unisex lanzada en 2022. Equilibrio intrigante de notas especiadas audaces y verdes frescas que energizan los sentidos.', '/images/lattafa/safeer.avif', 'Fresh', 'Unisex', 'Pomelo, Bergamota, Pimienta negra, Jengibre', 'Caramelo, Jazmín, Heliotropo', 'Madera de guayaco, Almizcle, Cipriol, Ámbar gris, Cashmeran'),
('Liam', 'Lattafa', 'Fragancia ámbar oriental unisex lanzada en 2023, inspirada en Gris Charnel de BDK. Mezcla sofisticada de especias exóticas, resinas ricas y maderas cremosas.', '/images/lattafa/liam.avif', 'Oriental', 'Unisex', 'Cardamomo, Higo, Té negro', 'Iris, Vetiver, Ládano', 'Vainilla, Sándalo, Haba tonka, Pachulí'),
('Abaan', 'Lattafa', 'Fragancia floral amaderada almizclada lanzada en 2022.', '/images/lattafa/abaan.avif', 'Floral', 'Women', 'Bergamota, Naranja', 'Flor de naranjo, Jazmín', 'Sándalo, Pachulí, Almizcle'),
('Yara', 'Lattafa', 'Fragancia oriental vainillada lanzada en 2020.', '/images/lattafa/yara.avif', 'Oriental', 'Women', 'Orquídea, Heliotropo, Mandarina', 'Acorde gourmand, Frutas tropicales', 'Vainilla, Almizcle, Sándalo'),
('Lail Maleki', 'Lattafa', 'Fragancia oriental unisex lanzada en 2018.', '/images/lattafa/lail.avif', 'Oriental', 'Unisex', 'Notas frutales, Notas especiadas, Cítricos', 'Miel, Jazmín, Gardenia, Orquídea', 'Almizcle, Ámbar, Caramelo, Sándalo'),
('Hayaati Al Maleky', 'Lattafa', 'Fragancia oriental especiada unisex lanzada en 2022.', '/images/lattafa/hayaati-al-maleky.avif', 'Oriental', 'Unisex', 'Pimienta rosa, Bergamota, Jengibre, Nuez moscada', 'Cedro, Notas amaderadas, Incienso, Ládano', 'Almizcle, Ámbar gris, Ámbar'),
('24 Carat Pure Gold 999.9', 'Lattafa', 'Fragancia oriental vainillada unisex.', '/images/lattafa/24-carat-pure-gold.avif', 'Oriental Vanilla', 'Unisex', 'Oud, Azafrán, Canela', 'Rosa, Sándalo', 'Cuero, Incienso, Ámbar, Almizcle, Vainilla'),
('Hayaati Gold Elixir', 'Lattafa', 'Fragancia unisex con notas cítricas en la salida.', '/images/lattafa/hayaati-gold-elixir.avif', 'Oriental', 'Unisex', 'Bergamota, Pomelo, Grosella negra', 'Cuero, Melocotón, Azafrán', 'Vainilla, Ámbar, Almizcle, Vetiver'),
('Ramz Lattafa', 'Lattafa', 'Fragancia unisex frutal y amaderada.', '/images/lattafa/ramz.avif', 'Floral', 'Unisex', 'Manzana, Melocotón, Grosella negra, Pera', 'Rosa, Jazmín Sambac, Flor de naranjo', 'Sándalo, Almizcle blanco, Vainilla, Pachulí'),
('Ana Abiyedh Poudrée', 'Lattafa', 'Fragancia floral lanzada en 2023.', '/images/lattafa/ana-abiyedh.avif', 'Floral', 'Women', 'Flor de naranjo, Rosa, Jazmín', 'Almizcle', 'Vainilla, Haba tonka, Cedro'),
('Opulent Musk', 'Lattafa', 'Fragancia oriental lanzada en 2019.', '/images/lattafa/opulent-musk.avif', 'Oriental', 'Women', 'Almizcle blanco, Azafrán, Limón', 'Flores blancas, Jazmín', 'Almizcle blanco, Cedro, Ámbar'),
('Blue Oud', 'Lattafa', 'Fragancia ámbar amaderada unisex.', '/images/lattafa/opulent-blue-oud.avif', 'Oriental', 'Unisex', 'Oud, Pimienta negra, Manzana, Bergamota', 'Frutas, Azafrán, Almizcle', 'Ámbar gris, Sándalo'),
('Afeef', 'Lattafa', 'Fragancia unisex lanzada en 2024.', '/images/lattafa/afeef.avif', 'Floral', 'Unisex', 'Melocotón, Pimienta rosa, Bergamota', 'Tuberosa, Jazmín', 'Sándalo, Praliné, Ámbar'),
('Petra', 'Lattafa', 'Fragancia floral frutal gourmand unisex.', '/images/lattafa/petra.avif', 'Floral Fruity Gourmand', 'Unisex', 'Ron, Ciruela', 'Tuberosa, Coco', 'Vainilla, Almizcle, Praliné'),
('Atheeri', 'Lattafa', 'Fragancia oriental floral lanzada en 2025.', '/images/lattafa/atheeri.avif', 'Floral', 'Women', 'Flor de la pasión', 'Orquídea, Jazmín', 'Vainilla, Amberwood'),
('Victoria', 'Lattafa', 'Fragancia floral gourmand unisex.', '/images/lattafa/victoria.avif', 'Floral', 'Unisex', 'Lemon Meringue Pie', 'Neroli', 'Vainilla'),
('Khamrah Dukhan', 'Lattafa', 'Fragancia oriental lanzada en 2025.', '/images/lattafa/khamrah-dukhan.avif', 'Oriental', 'Men', 'Especias, Mandarina', 'Incienso, Pachulí', 'Tabaco, Ámbar'),
('Maahir Legacy', 'Lattafa', 'Fragancia fresca masculina inspirada en Sedley.', '/images/lattafa/maahir-legacy.avif', 'Fresh', 'Men', 'Lima, Menta, Pomelo', 'Romero, Enebro', 'Ambroxan, Vetiver'),
('Al Nashama', 'Lattafa', 'Fragancia unisex inspirada en Paragon.', '/images/lattafa/al-nashama.avif', 'Oriental', 'Unisex', 'Pimienta rosa, Bergamota', 'Ciruela, Jazmín', 'Ámbar, Pachulí'),
('The Kingdom', 'Lattafa', 'Fragancia aromática masculina.', '/images/lattafa/the-kingdom.avif', 'Oriental', 'Men', 'Lavanda, Menta', 'Vainilla', 'Haba tonka, Ámbar'),
('Khamrah', 'Lattafa', 'Fragancia oriental especiada unisex.', '/images/lattafa/khamrah.avif', 'Oriental', 'Unisex', 'Canela, Nuez moscada', 'Dátiles, Praliné', 'Vainilla, Tonka'),
('Khamrah Qahwa', 'Lattafa', 'Fragancia gourmand con café oscuro y adictivo.', '/images/lattafa/khamrah-qahwa.avif', 'Oriental Vanilla', 'Unisex', 'Canela, Cardamomo, Jengibre', 'Praliné, Flores blancas', 'Café, Vainilla, Tonka'),
('Asad Bourbon', 'Lattafa', 'Fragancia especiada masculina con toque boozy.', '/images/lattafa/asad-bourbon.avif', 'Oriental', 'Men', 'Lavanda, Mirabelle, Pimienta rosa', 'Cacao, Nuez moscada, Davana', 'Vainilla bourbon, Ámbar, Vetiver');

ALTER TABLE perfumes ADD COLUMN slug VARCHAR(255) UNIQUE AFTER name;

-- Generar slugs automáticamente desde el nombre
UPDATE perfumes SET slug = LOWER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(name, ' ', '-'), '.', ''), ',', ''), '(', ''), ')', ''), '''', ''));